apiVersion: apps/v1

kind: Deployment

metadata:

  name: elasticsearch
  namespace: kube-logging

  labels:

    app: elasticsearch

spec:

  replicas: 1

  selector:

    matchLabels:

      app: elasticsearch

  template:

    metadata:

      labels:

        app: elasticsearch

    spec:

      containers:

      - name: elasticsearch

        image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0

        

        env:

        - name: discovery.type

          value: single-node

        ports:

        - containerPort: 9200

          name: es-http

        - containerPort: 9300

          name: es-transport

        volumeMounts:

        - name: es-data

          mountPath: /usr/share/elasticsearch/data

      volumes:

      - name: es-data

        emptyDir: {}

 

---

 

apiVersion: v1

kind: Service

metadata:

  name: elasticsearch-service
  namespace: kube-logging


  labels:

    app: elasticsearch

spec:

  type: NodePort

  selector:

    app: elasticsearch

  ports:

  - port: 9200

    targetPort: 9200

    protocol: TCP

    name: es-http

  - port: 9300

    targetPort: 9300

    protocol: TCP

    name: es-transport
