apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
     namespace: default 
     name: pod-reader-role
rules:
   - apiGroups: [""]
     resources: ["pods"]
     verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
     name: pod-reader-binding
     namespace: default
subjects:
   - kind: User
     name: {{ .Values.user }} # Replace with the user's Azure AD identity
     apiGroup: rbac.authorization.k8s.io
roleRef:
     kind: Role
     name: pod-reader-role
     apiGroup: rbac.authorization.k8s.io




